package com.green.ward;

/**
 * Cumulative XP required per level, 1–50 (Design Program Update 2 § 2.3: "table-driven,
 * not formula-driven, so it can be tuned"). Generated by geometric (log-space)
 * interpolation between the spec's own four anchor points — level 1 at 50, level 10 at
 * ~10k, level 25 at ~180k, level 50 at 1.5M — then hand-frozen into this table so those
 * four levels land on the spec's numbers exactly and the shape between them is smooth.
 * A starting balance pass, same as every other numeric table in this project — free to
 * hand-edit any entry without touching the generating formula.
 */
final class SkillXpCurve {
    private SkillXpCurve() {}

    /** Index 0 = XP needed to reach level 1, index 49 = XP needed to reach level 50. */
    static final long[] CUMULATIVE_XP = {
            50, 90, 162, 292, 527, 949, 1710, 3081, 5550, 10000,
            12125, 14702, 17826, 21614, 26207, 31777, 38530, 46717, 56645, 68683,
            83279, 100976, 122434, 148453, 180000, 195932, 213274, 232151, 252699, 275066,
            299412, 325913, 354760, 386160, 420339, 457544, 498041, 542124, 590107, 642338,
            699192, 761078, 828442, 901768, 981584, 1068465, 1163036, 1265977, 1378029, 1500000
    };

    static int levelForXp(long cumulativeXp) {
        int level = 0;
        for (long threshold : CUMULATIVE_XP) {
            if (cumulativeXp >= threshold) {
                level++;
            } else {
                break;
            }
        }
        return Math.min(level, GreenwardSkill.MAX_LEVEL);
    }

    static long xpForLevel(int level) {
        if (level <= 0) {
            return 0;
        }
        return CUMULATIVE_XP[Math.min(level, GreenwardSkill.MAX_LEVEL) - 1];
    }
}
